version: "3.8"

services:
  mongodb:
    image: mongo:4.2.15
    command: --wiredTigerCacheSizeGB 1
    restart: always
    environment:
      MONGO_DB: pwndoc
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend-internal

  pwndoc-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mongodb
    environment:
      DB_SERVER: mongodb
      DB_NAME: pwndoc
      LT_URL: http://pwndoc-languagetools:8010
      LT_API_URL: http://pwndoc-languagetools:8020
    ports:
      - "4242:4242"
    networks:
      - backend-internal
      - frontend-internal

  pwndoc-languagetools:
    build:
      context: ./languagetool
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - pwndoc-backend
    environment:
      BACKEND_URL: http://pwndoc-backend:4242
    volumes:
      - ./languagetool/custom-rules:/LanguageTool/custom-rules
    networks:
      - backend-internal

  pwndoc-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - pwndoc-backend
    ports:
      - "8080:80"
      - "8443:8443"
    networks:
      - frontend-internal

networks:
  backend-internal:
    driver: bridge
  frontend-internal:
    driver: bridge

volumes:
  mongodb_data:
